database:
  user: druid      # Postgres admin username
  password: diurd  # Postgres admin password
  host: localhost  # Postgres host address
  port: 5432       # Postgres host port
  db: druid        # Postgres metatdata database for Druid cluster

s3:
  bucket: my-druid-bucket  # S3 bucket name for Druid metadata
  keyBase: indexing-logs   # Path in bucket to indexing logs 
  batchSize: 1000          # How many objects to delete from S3 at a time

endTime: "2021-09-01"  # The end created_date to delete metadata up to
